# Generated by Django 4.0.6 on 2022-07-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_courses_options_alter_departments_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='programme_code',
            field=models.CharField(default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='entry_num',
            field=models.CharField(max_length=11, null=True, verbose_name='Entry Number'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='kerberos_id',
            field=models.CharField(max_length=9, null=True, verbose_name='Kerberos ID'),
        ),
    ]
