# Generated by Django 4.0.6 on 2022-07-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
